######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 9 17:29:34 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 01SpinBoxSlider.cpp
