######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 2 17:36:31 2018
######################################################################
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ticker.h

SOURCES += \
    ticker.cpp \
    main.cpp
